ALTER TABLE fields
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS size VARCHAR(255),
  ADD COLUMN IF NOT EXISTS photo_url VARCHAR(1000),
  ADD COLUMN IF NOT EXISTS has_lights BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_parking BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_indoor BOOLEAN DEFAULT false;
